# Generated by Django 3.2.16 on 2023-01-19 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0002_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='following',
        ),
        migrations.AddField(
            model_name='socialuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
