# Generated by Django 3.2.16 on 2023-01-19 02:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_auto_20230119_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='following',
        ),
        migrations.AddField(
            model_name='socialuser',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
