# Generated by Django 3.2.16 on 2023-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_auto_20230120_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
