# Generated by Django 3.2.16 on 2023-01-21 23:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_auto_20230121_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialuser',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='socialuser',
            name='age',
            field=models.IntegerField(blank=True, default=20, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
