# Generated by Django 3.2.16 on 2023-01-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_auto_20230121_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='profile_image',
            field=models.CharField(default='placeholder', max_length=100),
        ),
    ]
