# Generated by Django 3.2.16 on 2023-01-22 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_alter_socialuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(1)]),
        ),
    ]
