# Generated by Django 3.2.16 on 2023-01-24 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_alter_socialuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_social',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author_social', to='timeline.socialuser'),
            preserve_default=False,
        ),
    ]
