# Generated by Django 3.2.16 on 2023-01-28 19:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0013_comment_author_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='bio',
            field=models.TextField(default='No bio has been added yet...', max_length=200),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default="['testuser1']", null=True, size=None),
        ),
    ]
