# Generated by Django 3.2.16 on 2023-01-28 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_auto_20230128_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='following',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
